### ISSUE TITLE
Windowsにおける技リストの文字化け

### ISSUE THREAD

**Issue by yunkai1841** [sh-tak/PokemonishGame#21]
クライアントが受け取る技リストが文字化けする

> 技1: 技名: 繧ｯ繝ｭ繧ｹ繝輔Ξ繧､繝? 威力: 100 最大使用可能回数: 5 属性: 火 技種類: 物理命中率50
技2: 技名: 繧ｹ繝代?ｼ繧ｯ 威力: 65 最大使用可能回数: 20 属性: 光 技種類: 特殊命中率50
技3: 技名: 繧ｷ繝｣繝峨?ｼ繝懊?ｼ繝ｫ 威力: 80 最大使用可能回数: 15 属性: 闇 技種類: 物理命中率50
技4: 技名: 縺上＆縺ｮ縺｡縺九＞ 威力: 80 最大使用可能回数: 10 属性: 草 技種類: 物理命中率50

**Comment by sh-tak** [comment]
Utf-8をshift-jisで表示してるからっぽいから、技受けとったらshift-jisに変換したら多分いけるけど、そうすると今度はMacだとshift-jisをutf-8で表示することになってしまうので文字化けしてしまった。
